
version: "3.8"

services:

  brian-yolo-client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: brianbwire/brian-yolo-client:v1.0.0
    container_name: brian-yolo-client
    ports:
      - "3000:80"
    depends_on: 
      - brian-yolo-backend
    networks:
      - app-net

  brian-yolo-backend:
    image: brianbwire/brian-yolo-backend:v1.0.0
    build: ./backend
    container_name: brian-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - app-ip-mongo
    networks:
      - app-net

  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db


  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 


  app-mongo-data:
    driver: local