
version: "3.8"

services:

  brian-yolo-client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: brianbwire/brian-yolo-client:v1.0.0
    container_name: brian-yolo-client
    ports:
      - "3001:3000"
    environment:
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    depends_on: 
      - brian-yolo-backend
    networks:
      - app-net

  brian-yolo-backend:
    image: brianbwire/brian-yolo-backend:v1.0.0
    build: ./backend
    container_name: brian-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5001:5000"
    depends_on: 
      - app-ip-mongo
    networks:
      - app-net

  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27018:27017"
    networks:
      - app-net
    volumes:
      - app-mongo-data:/data/db

networks:
  app-net:
    driver: bridge


volumes:
  app-mongo-data: